---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: aubertit
description: My personal flavor of Bazzite Stable for a ASUS Laptops.
base-image: ghcr.io/ublue-os/bazzite-asus-nvida
image-version: stable

stages:
  - name: zram-generator
    from: fedora
    modules:
      - type: script
        scripts:
          - build-zram-generator.sh

modules:
  - from-file: configs/udevrules.yml
  - from-file: configs/systemfiles.yml
  - from-file: configs/zram-generator.yml

  - from-file: configs/sshd.yml
  - from-file: configs/fonts.yml
  - from-file: configs/power.yml
  - from-file: configs/packages.yml
  - from-file: configs/tailscale.yml

  - from-file: configs/bazzite.yml
  - from-file: configs/flatpaks.yml

  - type: signing
