---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: flaviramea
description: My personal flavor of Fedora Sway Atomic.
base-image: ghcr.io/ublue-os/sericea-main
image-version: latest

stages:
  - name: zram-generator
    from: fedora
    modules:
      - type: script
        scripts:
          - build-zram-generator.sh

modules:
  - from-file: configs/udevrules.yml
  - from-file: configs/systemfiles.yml
  - from-file: configs/zram-generator.yml

  - from-file: configs/podman.yml
  - from-file: configs/fonts.yml
  - from-file: configs/sshd.yml

  - from-file: configs/packages.yml
  - from-file: configs/flatpaks.yml
  - from-file: configs/homebrew.yml

  - type: signing
