#!/usr/bin/env bash
## https://devhints.io/bash
set -euo pipefail # strict
IFS=$'\n\t'

if ! command -v bluebuild >/dev/null; then
	echo "bluebuild CLI not found."
	exit 1
fi

if [ "$EUID" -ne 0 ]; then
	sudo $0 "$*"
	exit $?
fi

prfrrd="${1:-}"
outdir="${2:-$HOME/Images}"
mkdir -p "$outdir"
RECIPES=()
here="$PWD"
cd recipes
today=$(date -I)
RECIPES+=(recipe-*.yml)
for recipe in "${RECIPES[@]}"; do
	image="${recipe#recipe-}"
	image="${image%.yml}"
	if [[ -n "$prfrrd" ]] && ! [[ "$image" == "$prfrrd" ]]; then
		continue;
	fi
	cd "$here"
	if bluebuild generate "recipes/$recipe" --output "$outdir/$image-$today".yaml --display-full-recipe &&
		bluebuild generate "recipes/$recipe" --output "$outdir/$image-$today".Containerfile &&
		bluebuild generate-iso -V kinoite --output-dir "$outdir" --iso-name "$image-$today".iso image ghcr.io/omegasquad82/"$image"; then
		echo "$(ls "$outdir/$image-$today".{iso,Containerfile,yaml}) => rendered from $recipe and ostree-image-signed:docker://$image"
	else
		echo "ostree-image-signed:docker://$image from $recipe could not be turned into {iso,Containerfile,yaml} formats"
	fi
done
