#!/bin/bash
set -euo pipefail

if ! command -v bluebuild >/dev/null; then
	echo "bluebuild CLI not found."
	exit 1
fi

if [ "$EUID" -ne 0 ]; then
	echo "Must be run as root!"
	exit 2
fi

outdir=./isos
mkdir -p "$outdir"
IMAGES=()
here="$PWD"
cd recipes
IMAGES+=(recipe-*.yml)
for image in "${IMAGES[@]}"; do
	image="${image#recipe-}"
	image="${image%.yml}"
	cd "$here"
	if ! bluebuild generate-iso --output-dir "$outdir" --iso-name "$image-$(date -I)".iso image ghcr.io/omegasquad82/"$image"; then
		echo "ostree-image-signed:docker://$image could not be turned into an ISO"
		continue
	fi
done
