modules:
  - type: default-flatpaks
    notify: true
    user:
      install:
        - com.discordapp.Discord
        - org.openrgb.OpenRGB
  - type: systemd
    system:
      disabled:
        - tailscaled.service
