modules:
  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.synology.SynologyDrive
        - io.github.flattool.Warehouse
        - io.github.ungoogled_software.ungoogled_chromium
        - org.keepassxc.KeePassXC
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - org.signal.Signal
