modules:
  - type: dnf
    repos:
      copr:
        - hhd-dev/hhd
    install:
      packages:
        - adjustor
        - hhd
        - hhd-ui
  - type: systemd
    system:
      masked:
        - cpupower.service
        - power-profiles-daemon.service
        - tuned.service
