modules:
  - type: dnf
    install:
      packages:
        - repo: https://copr.fedorainfracloud.org/coprs/hhd-dev/hhd/repo/fedora-%OS_VERSION%/hhd-dev-hhd-fedora-%OS_VERSION%.repo
          packages:
            - adjustor
            - hhd
            - hhd-ui
  - type: systemd
    system:
      masked:
        - cpupower.service
        - power-profiles-daemon.service
        - tuned.service
