modules:
  - type: rpm-ostree
    install:
      - https://github.com/rmcrackan/Libation/releases/download/v11.1.0/Libation.11.1.0-linux-chardonnay-amd64.rpm
      - libvirt
      - qemu
  - type: default-flatpaks
    notify: true
    system:
      install:
        - app.devsuite.Ptyxis
        - com.logseq.Logseq
        - com.vscodium.codium
        - de.bund.ausweisapp.ausweisapp2
        - io.github.dvlv.boxbuddyrs
        - io.github.nroduit.Weasis
        - md.obsidian.Obsidian
        - org.fedoraproject.MediaWriter
