modules:
  - type: rpm-ostree
    install:
      - https://github.com/rmcrackan/Libation/releases/download/v11.6.4/Libation.11.6.4-linux-chardonnay-amd64.rpm
  - type: default-flatpaks
    notify: true
    system:
      install:
        - app.devsuite.Ptyxis
        - com.calibre-ebook.calibre
        - com.logseq.Logseq
        - com.vscodium.codium
        - de.bund.ausweisapp.ausweisapp2
        - io.github.dvlv.boxbuddyrs
        - io.github.nroduit.Weasis
        - md.obsidian.Obsidian
        - org.fedoraproject.MediaWriter
