modules:
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - app.devsuite.Ptyxis
          - com.calibre_ebook.calibre
          - com.logseq.Logseq
          - com.vscodium.codium
          - de.bund.ausweisapp.ausweisapp2
          - io.github.dvlv.boxbuddyrs
          - io.github.nroduit.Weasis
          - md.obsidian.Obsidian
          - org.fedoraproject.MediaWriter
