modules:
  - type: rpm-ostree
    install:
      - https://github.com/rmcrackan/Libation/releases/download/v12.2.0/Libation.12.2.0-linux-chardonnay-arm64.rpm
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/hhd-dev/hhd/repo/fedora-%OS_VERSION%/hhd-dev-hhd-fedora-%OS_VERSION%.repo
    install:
      - adjustor
      - hhd
      - hhd-ui
  - type: systemd
    user:
      enabled:
        - hhd
  - type: default-flatpaks
    notify: true
    system:
      install:
        - app.devsuite.Ptyxis
        - com.calibre_ebook.calibre
        - com.logseq.Logseq
        - com.vscodium.codium
        - de.bund.ausweisapp.ausweisapp2
        - io.github.dvlv.boxbuddyrs
        - io.github.nroduit.Weasis
        - md.obsidian.Obsidian
        - org.fedoraproject.MediaWriter
