modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/rodoma92/rmlint/repo/fedora-%OS_VERSION%/rodoma92-rmlint-fedora-%OS_VERSION%.repo
    install:
      - byobu
      - htop
      - kitty
      - neovim
      - rmlint
