modules:
  - type: dnf
    install:
      packages:
        - tuned
  - type: systemd
    system:
      masked:
        - cpupower.service
      unmasked:
        - tuned.service
  - type: systemd
    system:
      enabled:
        - tuned.service
