modules:
  - type: rpm-ostree
    install:
      - tuned
    remove:
      - powertop
  - type: systemd
    system:
      masked:
        - cpupower.service
      unmasked:
        - tuned.service
  - type: systemd
    system:
      enabled:
        - tuned.service
  - type: script
    snippets:
      - "tuned-adm recommend && tuned-adm auto_profile && tuned-adm profile_info"
