stages:
  - name: build
    from: fedora
    modules:
      - type: script
        scripts:
          - build-zram-generator.sh
modules:
  - type: copy
    from: build
    src: /root/.cargo/bin/zram-generator
    dest: /usr/lib/systemd/system-generators/zram-generator
  - type: systemd
    system:
      enabled:
        - zram-recompression.timer
