modules:
  - type: copy
    from: zram-generator
    src: /root/.cargo/bin/zram-generator
    dest: /usr/lib/systemd/system-generators/zram-generator
  - type: systemd
    system:
      enabled:
        - zram-recompression.timer
