modules:
  - type: rpm-ostree
    install:
      - zram-generator-defaults
  - type: systemd
    system:
      enabled:
        - zram-idling.timer
        - zram-compaction.timer
        - zram-recompression.timer
