name: bluebuild
on:
  schedule:
    - cron:
        "05 06 * * *" # build at 06:05 UTC every day
        # (25 minutes after last ublue images start building)
  push:
    paths-ignore:
      - "**.md"
      - "**/trivy.yml"
  pull_request:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - aubertit
          - borealis
          - buttgenbachit
          - carbonatcyanotrichit
          - flaviramea
        # - template
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: echo "IMAGE_REF=${REGISTRY}:${OWNER@L}/${{ matrix.package }}" >> ${GITHUB_ENV}
      - run: docker pull ${{ env.IMAGE_REF }}
      - name: Build Custom Image
        uses: blue-build/github-action@v1.6
        with:
          recipe: recipe-${{ matrix.package }}.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: false
