name: bluebuild
on:
  schedule:
    - cron:
        "05 06 * * *" # build at 06:05 UTC every day
        # (25 minutes after last ublue images start building)
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - file: recipe-aubertit.yml
            name: aubertit
          - file: recipe-borealis.yml
            name: borealis
          - file: recipe-buttgenbachit.yml
            name: buttgenbachit
          - file: recipe-carbonatcyanotrichit.yml
            name: carbonatcyanotrichit
          - file: recipe-flaviramea.yml
            name: flaviramea
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.6
        with:
          recipe: ${{ matrix.recipe.file }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/${{ matrix.recipe.name }}"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH,MEDIUM"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
