name: bluebuild
on:
  schedule:
    - cron:
        "05 06 * * *" # build at 06:05 UTC every day
        # (25 minutes after last ublue images start building)
  push:
    paths-ignore:
      - "**.md"
      - "build-isos"
      - "**/trivy.yml"
  workflow_dispatch:
env:
  REPO_OWNER: ${{ github.repository_owner }}
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        package:
          #- aubertit
          #- borealis
          - buttgenbachit
          - carbonatcyanotrichit
          - flaviramea
    steps:
      - name: get default branch
        run: echo "DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')" >> $GITHUB_ENV
      - name: check if on default (main) branch, only then rechuck the image
        run: if [[ "{{ github.ref_name }}" = "$DEFAULT_BRANCH" || "{{ github.ref_name }}" = 'rechunk' ]]; then echo "IS_DEFAULT=true" >> $GITHUB_ENV; fi
      - name: Build Custom Image
        uses: blue-build/github-action@v1.8
        with:
          rechunk: "${{ env.IS_DEFAULT }}"
          recipe: recipe-${{ matrix.package }}.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: yes
