name: build-image
on:
  workflow_dispatch: # allow manually triggering builds
  push:
    paths-ignore:
      - "**/release-please.yml"
      - "**/vulnerability-scan.yml"
      - "**/composition-analysis.yml"
      - "**.md"
      - "**/.gitkeep"
      - "build-isos"
      - "renovate.json"
  schedule:
    - cron:
        "25 06 * * 1,3,5" # build at 06:10 UTC on Mon, Wed, Fr
        # (45 minutes after last ublue images start building)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  HOMESPACE_OWNER:
  IS_DEFAULT: false
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  REGISTRY_IMG_PATH: ghcr.io/${{ github.repository_owner }}
  IMAGE_REF:

jobs:
  imagebuild:
    name: Build Custom Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true
      matrix:
        package:
          - aubertit
          - buttgenbachit
          - carbonatcyanotrichit
          - flaviramea
    steps:
      - run: id
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: true
          remove-android: true
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true
      - name: Compress critical paths
        shell: bash
        run: |
          set -euo pipefail

          # https://github.com/easimon/maximize-build-space/issues/23
          # https://github.com/easimon/maximize-build-space/pull/37
          WORKSPACE_OWNER="$(stat -c '%U:%G' "${GITHUB_WORKSPACE}")"
          HOMESPACE_OWNER="$(stat -c '%U:%G' "${HOME}")" | tee >>"$GITHUB_ENV"

          VG_NAME=buildvg
          LV_NAME=buildlv
          LV_PATH="/dev/mapper/${VG_NAME}-${LV_NAME}"

          cd ~
          sudo umount "${LV_PATH}"
          sudo mkdir -p /btrfsrootvol "${HOME}"/.local/share/containers /var/lib/containers /sysroot

          # https://github.com/radxa/armbian-compile-action/commit/82fe40188f2f3b4dbd4ae8fb9c64f49f117085c7
          sudo mkfs.btrfs -L "${LV_NAME}" -M -m single --force "${LV_PATH}"
          sudo mount -o defaults,noatime,compress=zstd:1,discard=sync "${LV_PATH}" /btrfsrootvol

          cd /btrfsrootvol
          for subvolume in containers homestorge ostreestor aworkspace; do
            sudo btrfs subvolume create "$subvolume"
          done

          # https://github.com/containers/podman/blob/main/troubleshooting.md#11-changing-the-location-of-the-graphroot-leads-to-permission-denied
          sudo mount -o subvol=containers,noatime,compress=zstd:1,discard=sync "${LV_PATH}" /var/lib/containers
          sudo mount -o subvol=homestorge,noatime,compress=zstd:1,discard=sync "${LV_PATH}" "${HOME}"/.local/share/containers
          sudo mount -o subvol=ostreestor,noatime,compress=zstd:1,discard=sync "${LV_PATH}" /sysroot
          sudo mount -o subvol=aworkspace,noatime,compress=zstd:1,discard=sync "${LV_PATH}" "${GITHUB_WORKSPACE}"

          sudo chown -R "$WORKSPACE_OWNER" "${GITHUB_WORKSPACE}"
          sudo chown -R "$HOMESPACE_OWNER" "${HOME}"/.local/share/containers

          sudo mount | grep btrfs
          lsblk

      - run: df -h && du -sh /* 2>/dev/null || true

      - name: Check if on default (main) or test (rechunk) branch to rechunk it
        run: |
          if [[ '${{ github.ref_name }}' == '${{ github.event.repository.default_branch }}' || '${{ github.ref_name }}' == 'rechunk' ]]; then
            echo 'IS_DEFAULT=true'>$GITHUB_ENV
          fi

      - name: Build Custom Image
        uses: blue-build/github-action@v1.8.1
        with:
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          maximize_build_space: ${{ env.IS_DEFAULT }}
          pr_event_number: ${{ github.event.number }}
          rechunk: ${{ env.IS_DEFAULT }}
          recipe: recipe-${{ matrix.package }}.yml
          registry_token: ${{ github.token }}
          # build_args: |
          #   --compression-format zstd:chunked

      - run: df -h && du -sh /* 2>/dev/null || true

      - name: Run podman login ghcr.io
        run: |
          set -euo pipefail

          # https://github.com/containers/podman/issues/5049#issuecomment-1348628646
          sudo chown -R "${{ env.HOMESPACE_OWNER }}" /run/user/"$UID"
          loginctl enable-linger "$USER"

          podman login ghcr.io \
            --username "${{ env.REGISTRY_USERNAME }}" \
            --password "${{ env.REGISTRY_PASSWORD }}"

      # https://github.com/orgs/community/discussions/10553#discussioncomment-11066950
      - name: Construct an image reference for ghcr.io
        run: echo "IMAGE_REF=${REGISTRY_IMG_PATH@L}/${{ matrix.package }}" >>$GITHUB_ENV

      - name: Run podman pull ${{ env.IMAGE_REF }}
        run: podman pull ${{ env.IMAGE_REF }}
      - name: Run podman history ${{ env.IMAGE_REF }}
        run: podman history ${{ env.IMAGE_REF }}
      - run: podman images --digests
      - run: podman info

      # This is something the community worked on for quite some time
      #   but it likely will improve the efficiency of transfers;
      #    this was made to workaround the fact that blue-build
      #     does not yet support zstd:chunked and it depends
      #      on bootc/rpm-ostree having implemented this,
      #       which according to my tests is now good.
      #
      # Changetracker
      #   https://fedoraproject.org/wiki/Changes/zstd:chunked
      #   https://github.com/containers/storage/pull/775
      # Documentation
      #   https://bootc-dev.github.io/bootc/filesystem-storage.html
      #   https://eu-os.eu/goals#goals # interesting new project
      # Projectstuffz
      #   https://github.com/blue-build/cli/issues/112
      #   https://github.com/containers/bootc/issues/20
      #   https://github.com/containers/bootc/issues/963
      - name: Recompress latest from gzip to zstd:chunked
        run: |
          set -euo pipefail

          echo "${{ secrets.SIGNING_SECRET }}" >cosign.key

          # https://github.com/containers/image/issues/1613#issuecomment-1188923320
          # https://github.com/containers/image/blob/main/docs/containers-registries.d.5.md#individual-configuration-sections
          PODMAN_CONFDIR="$HOME/.config/containers/registries.d"
          PODMAN_CONFIG="${PODMAN_CONFDIR}/registries.yaml"

          mkdir -p "${PODMAN_CONFDIR}"
          echo "creating: ${PODMAN_CONFIG}"
          tee "${PODMAN_CONFIG}" <<EOF
          default-docker:
            use-sigstore-attachments: true
          EOF

          podman push \
            --remove-signatures \
            --compression-format=zstd:chunked \
            --sign-by-sigstore-private-key=cosign.key \
            "$(podman image list --digests --format json | jq -r '.[0].Id')" \
            "${{ env.IMAGE_REF }}":latest-zstchd

      - run: df -h && du -sh /* 2>/dev/null || true
