name: composition-analysis
on:
  workflow_dispatch: # allow manually triggering builds
  push:
    paths-ignore:
      - "**/build-image.yml"
      - "**/release-please.yml"
      - "**/recompress-latest.yml"
      - "**/vulnerability-scan.yml"
      - "**.md"
      - "**/.gitkeep"
      - "build-isos"
      - "renovate.json"
  schedule:
    - cron:
        "00 07 * * 1,3,5" # scan at 07:00 UTC on Mon, Wed, Fr
        # (1 hour after bluebuild images started building)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  REGISTRY_IMG_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  analysis:
    name: Analyze Custom Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      security-events: write
    strategy:
      fail-fast: true
      matrix:
        package:
          - aubertit
          - buttgenbachit
          - carbonatcyanotrichit
          - flaviramea
    steps:
      - name: Checkout codeZ
        uses: actions/checkout@v4

      - name: Construct lowercase image reference
        run: echo "IMAGE_REF=${REGISTRY_IMG_PATH@L}/${{ matrix.package }}:latest" >> ${GITHUB_ENV}

      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        id: ort
        with:
          sw-name: ${{ matrix.package }}

      - name: Run GitHub Action for Tern
        uses: philips-labs/tern-action@v1.1.0
        id: tern
        with:
          image: ${{ env.IMAGE_REF }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}
          path: ${{ steps.tern.outputs.file }}

      - name: Print outputs
        run: |
          echo "${{ toJSON(steps.ort.outputs) }}" | jq .
          echo "${{ toJSON(steps.tern.outputs) }}" | jq .
