name: bluevuln
on:
  schedule:
    - cron:
        "55 06 * * *" # build at 06:55 UTC every day
        # (50 minutes after custom image build was triggered)
  pull_request:
  registry_package:
  workflow_dispatch:
env:
  REPO_OWNER: ${{ github.repository_owner }}
jobs:
  trivy:
    name: Scan Custom Image
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - aubertit
          - borealis
          - buttgenbachit
          - carbonatcyanotrichit
          - flaviramea
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Force repository owner to lowercase
        run: echo "IMAGE_REF=ghcr.io/${REPO_OWNER@L}/${{ matrix.package }}" >> ${GITHUB_ENV}

      - name: Generate tarball from image
        run: |
          docker pull ${{ env.IMAGE_REF }}
          docker save -o vuln-image.tar ${{ env.IMAGE_REF }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/vuln-image.tar
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          format: sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
