name: bluevuln
on:
  schedule:
    - cron:
        "55 06 * * *" # build at 06:55 UTC every day
        # (50 minutes after custom image build was triggered)
  pull_request:
  workflow_dispatch:
env:
  REPO_OWNER: ${{ github.repository_owner }}
jobs:
  scan:
    name: Scan Custom Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - aubertit
          - borealis
          - buttgenbachit
          - carbonatcyanotrichit
          - flaviramea
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Force repository owner to lowercase
        run: echo "IMAGE_REF=ghcr.io/${REPO_OWNER@L}/${{ matrix.package }}" >> ${GITHUB_ENV}

      - name: Generate SARIF for Custom Image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          output: ${{ matrix.package }}-trivy-results.sarif
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          image-ref: "${{ env.IMAGE_REF }}"
          severity: MEDIUM,HIGH,CRITICAL
          scan-type: image
          scanners: vuln
          format: sarif
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ github.token }}
      - uses: actions/cache/save@v4
        with:
          path: ${{ matrix.package }}-trivy-results.sarif
          key: ${{ runner.os }}-${{ github.run_id }}-${{ matrix.package }}
  upload:
    needs: scan
    name: Upload SARIF reports
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: read
      id-token: write
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: aubertit-trivy-results.sarif
          key: ${{ runner.os }}-${{ github.run_id }}-aubertit
      - uses: actions/cache/restore@v4
        with:
          path: borealis-trivy-results.sarif
          key: ${{ runner.os }}-${{ github.run_id }}-borealis
      - uses: actions/cache/restore@v4
        with:
          path: buttgenbachit-trivy-results.sarif
          key: ${{ runner.os }}-${{ github.run_id }}-buttgenbachit
      - uses: actions/cache/restore@v4
        with:
          path: carbonatcyanotrichit-trivy-results.sarif
          key: ${{ runner.os }}-${{ github.run_id }}-carbonatcyanotrichit
      - uses: actions/cache/restore@v4
        with:
          path: flaviramea-trivy-results.sarif
          key: ${{ runner.os }}-${{ github.run_id }}-flaviramea

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .
