name: bluevuln
on:
  schedule:
    - cron:
        "55 06 * * *" # build at 06:55 UTC every day
        # (50 minutes after custom image build was triggered)
  registry_package:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
jobs:
  trivy:
    name: Scan Custom Image
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - aubertit
          - borealis
          - buttgenbachit
          - carbonatcyanotrichit
          - flaviramea
        # - template
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: echo "IMAGE_REF=${REGISTRY}:${OWNER@L}/${{ matrix.package }}" >> ${GITHUB_ENV}
      - run: docker pull ${{ env.IMAGE_REF }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_REF }}
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH,MEDIUM
        #env:
        #  TRIVY_USERNAME: ${{ github.actor }}
        #  TRIVY_PASSWORD: ${{ github.token }}
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
